export interface MaterialIcons {
  account_box?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  account_circle?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  announcement?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  camera?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  camera_enhance?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  favorite?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  favorite_border?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  home?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  search?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  power_off?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  power?: (AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
}
export interface AccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity {
  path: string;
  fill?: string | null;
}
